// Ported from gestimo's config/locales/{es,pt,en}.yml (pages.mercado.*).
// Numeric values/targets (bar widths, ring fills, hardcoded stat numbers)
// are language-invariant in the source ERB templates -- only labels and
// sources are translated -- so those live outside `copy` in Body.astro.
export type Lang = 'es' | 'pt' | 'en';

export const copy: Record<Lang, any> = {
  es: {
    meta: {
      title: 'Mercado Alquiler España y Portugal 2026 — Estadísticas e Informe',
      description: 'Estudio mercado alquiler España 2026: precio medio €14,7/m², nuevos contratos +15% interanual, jóvenes destinan 92,3% del salario. Datos Idealista, Fotocasa, CaixaBank y Banco de España.',
      updated: 'Actualizado en marzo de 2026',
      sourcesBrief: 'Idealista · Fotocasa · CaixaBank · Banco de España · CJE',
    },
    hero: {
      headline: 'Los propietarios pagan el precio de un sistema que falla a todos.',
      hookLabel: 'de los propietarios temen el impago',
      scrollCue: 'Ver los datos',
    },
    pulse: {
      overburden: { label: 'Inquilinos sobrecargados — España', source: 'CaixaBank · 2023' },
      householdsRent: { label: 'Hogares en alquiler — España', source: 'BdE · 2024' },
      priceIncome: { label: 'Años de renta para comprar una vivienda', source: 'BdE · T3 2025' },
      avgRentSpain: { label: 'Alquiler medio — España', source: 'Obs. Alquiler · 2025' },
    },
    spain: {
      heading: 'La presión sobre los inquilinos españoles',
      overburdenHeading: 'Inquilinos que gastan más del 40% de sus ingresos en vivienda',
      overburdenSpainLabel: 'España',
      overburdenEuLabel: 'Media UE',
      overburdenContext: '1 de cada 3 inquilinos en España está financieramente sobrecargado. La media de la UE es del 20,3%.',
      pressureCards: {
        askingPrice: { value: '+19,9%', label: 'Alquiler solicitado interanual', source: 'Fotocasa · Feb 2026' },
        demand: { value: '17', label: 'Interesados por anuncio', source: 'Idealista · T2 2025' },
        supply: { value: '-4,7%', label: 'Variación oferta de alquiler interanual', source: 'Obs. Alquiler · 2025' },
      },
    },
    cities: {
      heading: 'El coste del alquiler por ciudad — España',
      subheading: 'Dos fuentes independientes confirman que los precios siguen subiendo.',
      legendIdealista: 'Idealista · Dic 2025',
      legendFotocasa: 'Fotocasa · Feb 2026',
      madridLabel: 'Madrid',
      barcelonaLabel: 'Barcelona / Cataluña',
      balearesLabel: 'Baleares',
      nationalLabel: 'Media nacional',
      sourceNote: 'Alquiler solicitado por m². La barra de Barcelona muestra la región de Cataluña (Fotocasa). Baleares: solo Fotocasa.',
      accessibleSummary: 'Alquiler solicitado por m²: Madrid €22,7 (Idealista) y €21,17 (Fotocasa); Barcelona/Cataluña €23,8 (Idealista) y €19,38 (Fotocasa); Baleares €18,53 (Fotocasa); Media nacional €14,7 (Idealista) y €14,46 (Fotocasa).',
      trends: {
        heading: 'La tendencia detrás de los números',
        newContracts: { value: '+15%', label: 'Nuevos contratos de alquiler interanual', source: 'CaixaBank · finales 2025' },
        accumulation: { value: '+30%', label: 'Subida acumulada desde 2019', source: 'CaixaBank · H1 2025' },
        yield: { value: '7,02%', label: 'Rentabilidad bruta — España', source: 'Banco de España · Dic 2025' },
      },
    },
    youth: {
      heading: 'Los jóvenes no pueden permitirse irse de casa',
      framing: 'No por falta de ganas — simplemente los números no cuadran.',
      statLabel: 'del salario de los menores de 30 años necesario para alquilar solo — España',
      statSource: 'Consejo de la Juventud de España · 2025',
      emancipationStat: '15,2%',
      emancipationLabel: 'Tasa de emancipación juvenil (mínimo histórico)',
      emancipationSource: 'CJE Observatorio de Emancipación · H2 2025',
      context: 'El mercado de alquiler está excluyendo a toda una generación de la vida independiente. Los propietarios se enfrentan a un grupo cada vez más reducido de inquilinos con capacidad financiera — lo que hace que verificar a los que sí pueden pagar sea aún más crítico.',
    },
    portugal: {
      heading: 'El coste del alquiler en Portugal',
      framing: 'Los nuevos contratos de alquiler en Lisboa cuestan el doble que la media nacional — y la brecha se amplía.',
      lisbonLabel: 'Lisboa (nuevos contratos)',
      nationalLabel: 'Media nacional',
      source: 'INE Portugal · H2 2023',
      dataNote: 'Solo cubre nuevos contratos de alquiler. No se incluyen contratos existentes.',
    },
    risk: {
      heading: 'Casi la mitad de los propietarios están preocupados',
      statLabel: 'de los propietarios desconfían de los posibles inquilinos',
      context: '8 puntos más en un año. Las herramientas que usan la mayoría de propietarios — nóminas, documentos, intuición — no pueden seguir el ritmo de un mercado tan ajustado.',
      points: [
        'Los alquileres suben más rápido que los ingresos, lo que significa inquilinos más endeudados',
        'La alta demanda obliga a los propietarios a decidir más rápido, con menos tiempo para verificar',
        'Las comprobaciones basadas en documentos no muestran el cuadro real — los datos bancarios sí',
      ],
      cta: 'Descubre cómo Abitamo verifica inquilinos →',
      source: 'Fotocasa Research · 2025',
    },
    faq: {
      heading: 'Preguntas frecuentes',
      items: [
        { question: '¿Cuánto cuesta el alquiler medio en España en 2026?', answer: 'El alquiler medio en España es de €1.184/mes según el Observatorio del Alquiler (2025). En términos de precio por m², Idealista registró €14,7/m² (diciembre 2025) y Fotocasa €14,46/m² (febrero 2026). Los nuevos contratos de alquiler suben un 15% interanual, y los alquileres han aumentado un 30% desde 2019 (CaixaBank Research).' },
        { question: '¿Cuánto cuesta alquilar en Madrid y Barcelona en 2026?', answer: 'Los alquileres de oferta en Madrid alcanzan €22,7/m² (Idealista, diciembre 2025) y €21,17/m² (Fotocasa, febrero 2026). Barcelona llega a €23,8/m² (Idealista, diciembre 2025), el precio más alto de cualquier gran ciudad española. Ambas ciudades se sitúan aproximadamente un 50–60% por encima de la media nacional.' },
        { question: '¿Cuánto han subido los alquileres en España desde 2019?', answer: 'Según CaixaBank Research, los alquileres en nuevos contratos han subido un 30% acumulado desde 2019. En términos interanuales, los precios de nuevos contratos crecieron un 15% a finales de 2025. El índice de precios de oferta de Idealista registró un crecimiento anual del 8,5% en diciembre de 2025.' },
        { question: '¿Cuál es la rentabilidad bruta del alquiler en España en 2026?', answer: 'La rentabilidad bruta del alquiler en España alcanzó el 7,02% en diciembre de 2025, según el Banco de España — un nuevo máximo histórico, aproximadamente 1 punto porcentual por encima de 2024. Esto refleja que el crecimiento de los alquileres supera al de los precios de la vivienda en la mayoría de los mercados.' },
        { question: '¿Qué porcentaje de su salario dedican los jóvenes al alquiler en España?', answer: 'Los jóvenes menores de 30 años necesitan destinar el 92,3% de su salario para poder alquilar solos en España, según el Consejo de la Juventud de España (2025). Como consecuencia, la tasa de emancipación juvenil cayó al 15,2% en el segundo semestre de 2025 — un mínimo histórico. Solo 1 de cada 7 jóvenes españoles vive de forma independiente del hogar familiar.' },
      ],
    },
    sources: {
      heading: 'De dónde vienen estos datos',
      subheading: 'Cada número en esta página se extrae de fuentes institucionales públicas y se actualiza cada 2 meses.',
      automatedBadge: 'Automatizado',
      manualBadge: 'Manual',
    },
  },
  pt: {
    meta: {
      title: 'Mercado de Arrendamento Espanha e Portugal 2026 — Estatísticas e Estudo',
      description: 'Estudo do mercado de arrendamento 2026: renda média €14,7/m² em Espanha, novos contratos +15% AoA, jovens precisam de 92,3% do salário para arrendar sozinhos. Dados de Idealista, Fotocasa, CaixaBank e Banco de España.',
      updated: 'Atualizado em março de 2026',
      sourcesBrief: 'Idealista · Fotocasa · CaixaBank · Banco de España · CJE',
    },
    hero: {
      headline: 'O mercado de arrendamento não perdoa escolhas erradas.',
      hookLabel: 'dos senhorios temem falta de pagamento',
      scrollCue: 'Ver os dados',
    },
    pulse: {
      overburden: { label: 'Inquilinos sobreendividados — Espanha', source: 'CaixaBank · 2023' },
      householdsRent: { label: 'Famílias a arrendar — Espanha', source: 'BdE · 2024' },
      priceIncome: { label: 'Anos de rendimento para comprar casa', source: 'BdE · T3 2025' },
      avgRentSpain: { label: 'Renda média — Espanha', source: 'Obs. Alquiler · 2025' },
    },
    spain: {
      heading: 'A pressão sobre os inquilinos espanhóis',
      overburdenHeading: 'Inquilinos a gastar mais de 40% do rendimento em habitação',
      overburdenSpainLabel: 'Espanha',
      overburdenEuLabel: 'Média da UE',
      overburdenContext: '1 em cada 3 inquilinos em Espanha está financeiramente sobrecarregado. A média da UE é 20,3%.',
      pressureCards: {
        askingPrice: { value: '+19,9%', label: 'Renda pedida YoY', source: 'Fotocasa · Fev 2026' },
        demand: { value: '17', label: 'Interessados por anúncio', source: 'Idealista · T2 2025' },
        supply: { value: '-4,7%', label: 'Variação da oferta de arrendamento YoY', source: 'Obs. Alquiler · 2025' },
      },
    },
    cities: {
      heading: 'O custo do arrendamento por cidade — Espanha',
      subheading: 'Duas fontes independentes confirmam que os preços continuam a subir.',
      legendIdealista: 'Idealista · Dez 2025',
      legendFotocasa: 'Fotocasa · Fev 2026',
      madridLabel: 'Madrid',
      barcelonaLabel: 'Barcelona / Catalunha',
      balearesLabel: 'Baleares',
      nationalLabel: 'Média nacional',
      sourceNote: 'Renda pedida por m². Barra de Barcelona mostra a região da Catalunha (Fotocasa). Baleares: apenas Fotocasa.',
      accessibleSummary: 'Renda pedida por m²: Madrid €22,7 (Idealista) e €21,17 (Fotocasa); Barcelona/Catalunha €23,8 (Idealista) e €19,38 (Fotocasa); Baleares €18,53 (Fotocasa); Média nacional €14,7 (Idealista) e €14,46 (Fotocasa).',
      trends: {
        heading: 'A tendência por trás dos números',
        newContracts: { value: '+15%', label: 'Novos contratos de arrendamento AoA', source: 'CaixaBank · final 2025' },
        accumulation: { value: '+30%', label: 'Subida acumulada desde 2019', source: 'CaixaBank · H1 2025' },
        yield: { value: '7,02%', label: 'Rentabilidade bruta — Espanha', source: 'Banco de España · Dez 2025' },
      },
    },
    youth: {
      heading: 'Os jovens não conseguem sair de casa',
      framing: 'Não por falta de vontade — os números simplesmente não fecham.',
      statLabel: 'do salário de jovens com menos de 30 anos necessário para arrendar sozinho — Espanha',
      statSource: 'Consejo de la Juventud de España · 2025',
      emancipationStat: '15,2%',
      emancipationLabel: 'Taxa de emancipação juvenil (mínimo histórico)',
      emancipationSource: 'CJE Observatorio de Emancipación · H2 2025',
      context: 'O mercado de arrendamento está a excluir uma geração inteira da vida independente. Os senhorios enfrentam um conjunto cada vez mais reduzido de inquilinos financeiramente capazes — o que torna a verificação dos que podem pagar ainda mais crítica.',
    },
    portugal: {
      heading: 'O custo do arrendamento em Portugal',
      framing: 'Os novos contratos de arrendamento em Lisboa custam o dobro da média nacional — e o fosso está a aumentar.',
      lisbonLabel: 'Lisboa (novos contratos)',
      nationalLabel: 'Média nacional',
      source: 'INE Portugal · H2 2023',
      dataNote: 'Abrange apenas novos contratos de arrendamento. Contratos existentes não incluídos.',
    },
    risk: {
      heading: 'Quase metade dos senhorios está preocupada',
      statLabel: 'dos senhorios desconfiam de potenciais inquilinos',
      context: 'Mais 8 pontos em um ano. As ferramentas que a maioria dos senhorios usa — recibos de vencimento, documentos, intuição — não conseguem acompanhar um mercado tão competitivo.',
      points: [
        'Rendas a subir mais depressa do que os rendimentos significa inquilinos mais endividados',
        'Alta procura obriga senhorios a decidir mais rápido, com menos tempo para verificar',
        'Verificações baseadas em documentos não revelam o quadro real — os dados bancários sim',
      ],
      cta: 'Veja como o Abitamo verifica inquilinos →',
      source: 'Fotocasa Research · 2025',
    },
    faq: {
      heading: 'Perguntas frequentes',
      items: [
        { question: 'Quanto custa a renda média em Espanha em 2026?', answer: 'A renda média em Espanha é de €1.184/mês segundo o Observatorio del Alquiler (2025). Em termos de preço por m², o Idealista registou €14,7/m² (dezembro 2025) e o Fotocasa €14,46/m² (fevereiro 2026). Os novos contratos de arrendamento sobem 15% em termos homólogos, e as rendas aumentaram 30% desde 2019 (CaixaBank Research).' },
        { question: 'Quanto custa arrendar em Madrid e Barcelona em 2026?', answer: 'As rendas pedidas em Madrid atingem €22,7/m² (Idealista, dezembro 2025) e €21,17/m² (Fotocasa, fevereiro 2026). Barcelona chega aos €23,8/m² (Idealista, dezembro 2025), a mais alta de qualquer grande cidade espanhola. Ambas as cidades estão cerca de 50–60% acima da média nacional.' },
        { question: 'Quanto subiram as rendas em Espanha desde 2019?', answer: 'Segundo a CaixaBank Research, as rendas nos novos contratos subiram 30% de forma acumulada desde 2019. Em termos homólogos, os preços dos novos contratos cresceram 15% no final de 2025. O índice de preços de oferta do Idealista registou um crescimento anual de 8,5% em dezembro de 2025.' },
        { question: 'Qual é a rentabilidade bruta do arrendamento em Espanha em 2026?', answer: 'A rentabilidade bruta do arrendamento em Espanha atingiu 7,02% em dezembro de 2025, segundo o Banco de España — um novo máximo histórico, cerca de 1 ponto percentual acima de 2024. Isto reflete um crescimento das rendas superior ao crescimento dos preços das casas na maioria dos mercados.' },
        { question: 'Que percentagem do salário os jovens gastam em arrendamento em Espanha?', answer: 'Os jovens com menos de 30 anos precisam de 92,3% do salário para poder arrendar sozinhos em Espanha, segundo o Consejo de la Juventud de España (2025). Por isso, a taxa de emancipação juvenil caiu para 15,2% no segundo semestre de 2025 — um mínimo histórico. Apenas 1 em 7 jovens espanhóis vive de forma independente do lar familiar.' },
      ],
    },
    sources: {
      heading: 'De onde vêm estes dados',
      subheading: 'Cada número nesta página é extraído de fontes institucionais públicas e atualizado a cada 2 meses.',
      automatedBadge: 'Automatizado',
      manualBadge: 'Manual',
    },
  },
  en: {
    meta: {
      title: 'Spain & Portugal Rental Market 2026 — Statistics & Report',
      description: '2026 rental market study: average rent €14.7/m² in Spain, new contracts up 15% YoY, youth need 92.3% of salary to rent solo. Data from Idealista, Fotocasa, CaixaBank & Banco de España.',
      updated: 'Updated March 2026',
      sourcesBrief: 'Idealista · Fotocasa · CaixaBank · Banco de España · CJE',
    },
    hero: {
      headline: "The rental market doesn't forgive the wrong choice.",
      hookLabel: 'of landlords fear non-payment',
      scrollCue: 'See the data',
    },
    pulse: {
      overburden: { label: 'Renters over-burdened — Spain', source: 'CaixaBank · 2023' },
      householdsRent: { label: 'Households renting — Spain', source: 'BdE · 2024' },
      priceIncome: { label: 'Years of income to buy a home', source: 'BdE · Q3 2025' },
      avgRentSpain: { label: 'Average rent — Spain', source: 'Obs. Alquiler · 2025' },
    },
    spain: {
      heading: 'The pressure on Spanish renters',
      overburdenHeading: 'Renters spending over 40% of income on housing',
      overburdenSpainLabel: 'Spain',
      overburdenEuLabel: 'EU average',
      overburdenContext: '1 in 3 renters in Spain is financially over-stretched. The EU average is 20.3%.',
      pressureCards: {
        askingPrice: { value: '+19.9%', label: 'Asking rent YoY', source: 'Fotocasa · Feb 2026' },
        demand: { value: '17', label: 'Interested per listing', source: 'Idealista · Q2 2025' },
        supply: { value: '-4.7%', label: 'Rental supply change YoY', source: 'Obs. Alquiler · 2025' },
      },
    },
    cities: {
      heading: 'What renting costs by city — Spain',
      subheading: 'Two independent sources confirm prices keep climbing.',
      legendIdealista: 'Idealista · Dec 2025',
      legendFotocasa: 'Fotocasa · Feb 2026',
      madridLabel: 'Madrid',
      barcelonaLabel: 'Barcelona / Cataluña',
      balearesLabel: 'Baleares',
      nationalLabel: 'National avg',
      sourceNote: 'Asking rent per m². Barcelona bar shows Cataluña region (Fotocasa). Baleares: Fotocasa only.',
      accessibleSummary: 'Asking rent per m²: Madrid €22.7 (Idealista) and €21.17 (Fotocasa); Barcelona/Cataluña €23.8 (Idealista) and €19.38 (Fotocasa); Baleares €18.53 (Fotocasa); National average €14.7 (Idealista) and €14.46 (Fotocasa).',
      trends: {
        heading: 'The trend behind the numbers',
        newContracts: { value: '+15%', label: 'New rental contracts YoY', source: 'CaixaBank · late 2025' },
        accumulation: { value: '+30%', label: 'Cumulative rent rise since 2019', source: 'CaixaBank · H1 2025' },
        yield: { value: '7.02%', label: 'Gross rental yield — Spain', source: 'Banco de España · Dec 2025' },
      },
    },
    youth: {
      heading: "Young people can't afford to leave home",
      framing: "Not because they don't want to — the numbers simply don't add up.",
      statLabel: "of under-30s' salary needed to rent solo — Spain",
      statSource: 'Consejo de la Juventud de España · 2025',
      emancipationStat: '15.2%',
      emancipationLabel: 'Youth emancipation rate (historic low)',
      emancipationSource: 'CJE Observatorio de Emancipación · H2 2025',
      context: 'The rental market is pricing an entire generation out of independent living. Landlords face a shrinking pool of financially capable tenants — which makes verifying the ones who can pay even more critical.',
    },
    portugal: {
      heading: 'What renting costs in Portugal',
      framing: 'New rental contracts in Lisbon cost twice the national average — and the gap is widening.',
      lisbonLabel: 'Lisbon (new contracts)',
      nationalLabel: 'National average',
      source: 'INE Portugal · H2 2023',
      dataNote: 'Covers new rental contracts only. Existing contracts not included.',
    },
    risk: {
      heading: 'Nearly half of landlords are worried',
      statLabel: 'of landlords distrust potential tenants',
      context: "Up 8 points in one year. The tools most landlords use — payslips, documents, gut feel — can't keep up with a market this tight.",
      points: [
        'Rents rising faster than incomes means more financially stretched renters',
        'High demand means landlords must decide faster, with less time to verify',
        "Document-based checks miss the real picture — bank data doesn't",
      ],
      cta: 'See how Abitamo verifies renters →',
      source: 'Fotocasa Research · 2025',
    },
    faq: {
      heading: 'Frequently asked questions',
      items: [
        { question: 'How much does the average rent cost in Spain in 2026?', answer: 'The average rent in Spain is €1,184/month according to the Observatorio del Alquiler (2025). In per-m² terms, Idealista recorded €14.7/m² (December 2025) and Fotocasa recorded €14.46/m² (February 2026). New rental contracts are rising at 15% year-on-year, and rents have increased by 30% since 2019 (CaixaBank Research).' },
        { question: 'How much does rent cost in Madrid and Barcelona in 2026?', answer: 'Madrid asking rents average €22.7/m² (Idealista, December 2025) and €21.17/m² (Fotocasa, February 2026). Barcelona reaches €23.8/m² (Idealista, December 2025), the highest of any major Spanish city. Both cities sit roughly 50–60% above the national average.' },
        { question: 'How much has rent risen in Spain since 2019?', answer: 'According to CaixaBank Research, rents on new contracts have risen 30% cumulatively since 2019. Year-on-year, new contract prices grew 15% in late 2025. The official asking-price index from Idealista recorded 8.5% annual growth in December 2025.' },
        { question: 'What is the gross rental yield in Spain in 2026?', answer: 'The gross rental yield in Spain reached 7.02% in December 2025, according to the Banco de España — a new record high, up approximately 1 percentage point versus 2024. This reflects rent growth outpacing house price growth in most markets.' },
        { question: 'What percentage of their salary do young people spend on rent in Spain?', answer: 'Young people under 30 need 92.3% of their salary to afford solo renting in Spain, according to the Consejo de la Juventud de España (2025). As a result, the youth emancipation rate fell to 15.2% in the second half of 2025 — a historic low. Only 1 in 7 young Spaniards lives independently of the parental home.' },
      ],
    },
    sources: {
      heading: 'Where this data comes from',
      subheading: 'Every number on this page is extracted from public institutional sources and refreshed every 2 months.',
      automatedBadge: 'Automated',
      manualBadge: 'Manual',
    },
  },
};

// The 8 source cards' own content is hardcoded in English in the source
// ERB regardless of page locale (not run through i18n at all) -- ported
// faithfully rather than "fixed" unprompted.
export const sourceCards = [
  { name: 'INE Portugal', desc: 'Median rent/m² — Lisbon and national', date: 'H2 2023', url: 'https://www.ine.pt', urlLabel: 'ine.pt', badge: 'auto' },
  { name: 'INE España (IRAV)', desc: 'Legal rent update cap', date: 'Jan 2026', url: 'https://www.ine.es', urlLabel: 'ine.es', badge: 'auto' },
  { name: 'Banco de España', desc: 'Housing effort, price/income ratio, rental yield', date: 'Q3–Q4 2025', url: 'https://www.bde.es', urlLabel: 'bde.es', badge: 'auto' },
  { name: 'CaixaBank Research', desc: 'Rental overburden rate Spain vs EU', date: '2023', url: 'https://www.caixabankresearch.com', urlLabel: 'caixabankresearch.com', badge: 'auto' },
  { name: 'Fotocasa Research', desc: 'Landlord distrust rate, asking price YoY', date: '2025 / Feb 2026', url: 'https://www.fotocasa.es/fotocasa-life/investigacion', urlLabel: 'fotocasa.es', badge: 'auto' },
  { name: 'Idealista', desc: 'Interested parties per listing', date: 'Q2 2025', url: 'https://www.idealista.com/news/informes', urlLabel: 'idealista.com', badge: 'manual' },
  { name: 'Observatorio del Alquiler', desc: 'Average rent, supply change', date: '2025', url: 'https://www.observatoriovivienda.es', urlLabel: 'observatoriovivienda.es', badge: 'manual' },
  { name: 'Consejo de la Juventud de España', desc: 'Youth emancipation rate, salary effort for solo rent', date: 'H2 2025', url: 'https://www.cje.org', urlLabel: 'cje.org', badge: 'manual' },
];
